### ISSUE TITLE
allow more flexibility in handling of exposure events

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/mozanalysis#144]
while we want to bin clients into their branches only during the enrollment period, we (usually) want to bin them as exposed if the exposure event happens anytime after they are enrolled (or over some arbitrary observation period after the enrollment event, if we want to only count clients with "early enough" exposure). 

right now we bin clients as exposed only if the event happens during the enrollment period, i.e. here the `time_limits` parameter is re-used for both the enrollment and exposure events:

https://github.com/mozilla/mozanalysis/blob/b13f3e22511e52a49cad4459ef20c8445c93de0c/src/mozanalysis/experiment.py#L384

I think we want to enable two things WRT exposure events

1. allow arbitrary `exposure_time_limit`s for binning clients as exposed, which can be different from the enrollment period. depending on the context, a DS might want to allow exposure to happen anytime during the observation period, or maybe they only want to count clients as exposed if they trigger the event e.g. within the first 90% of observation period. 
2. in addition, count exposure events like a normal metric, where they are counted per-client-period.

For (1) I think this involves changing a couple things on the mozanalysis side, and then changing jetstream to allow custom exposure time_limits to be passed in when defining [ExposureSignalDefinition](https://github.com/mozilla/jetstream/blob/671117f02c5bde62d2cfaeb3de32b4932667a9a6/jetstream/config.py#L366-L384):

a. change the [ExposureSignal](https://github.com/mozilla/mozanalysis/blob/b13f3e22511e52a49cad4459ef20c8445c93de0c/src/mozanalysis/exposure.py) class to set exposure_time_limits as attributes, replacing `first/last_enrollment_date` in the query. this will allow these time limits to be passed in from jetstream.
b. change the references to [`exposure_signal.build_query()`](https://github.com/mozilla/mozanalysis/blob/a6d051ebcf487e9643d84b7c8ccde0217316090b/src/mozanalysis/experiment.py#L426) in the Experiment class to no longer pass in `time_limit` (this should be a parameter-less, or whatever you call it, function call now since the exposure_time_limits will be set when the `ExposureSignalDefinition` is instantiated)
c. we also need to the change the [tests](https://github.com/mozilla/mozanalysis/blob/main/tests/test_experiment.py)

for (2), we have the option of not doing anything, but requiring the DS to define the exposure events separately as metrics in either mozanalysis or jetstream. we could also do something to make sure these are treated as metrics automatically, but for now I'd say lets keep things simple - maybe we can document this somewhere. 

cc @scholtzan @rebecca-burwei

**Comment by rebecca-burwei** [comment]
There are 2 ways we might want to use the exposure to segment clients in an experiment:

1. A client is considered exposed for window_index = i  if the client sent an exposure ping for any day within window_index = i
2. A client is considered exposed for window_index = i if the client sent an exposure ping for any day within window_index = i, i-1, ..., 1, 0.

**Comment by scholtzan** [comment]
I did some prototyping for this and came up with a way to express more flexible exposures. The jetstream configuration would look something like:

```toml
[experiment.exposure_signal]
name = "nimbus"
friendly_name = "Nimbus exposure signal"
description = "Nimbus desktop feature exposure signal"
data_source = "events_unnested"
select_expression = "
   event_category = 'normandy'
   AND event_method = 'expose'
   AND event_object = 'nimbus_experiment'
   AND event_string_value = 'firefox-suggest-offline-vs-online'
   AND normalized_channel = 'release'
"

# these two parameters are new
window_start = "enrollment_start"
window_end = "analysis_window_end"


[data_sources.events_unnested]
from_expression = """(
  SELECT
    *
  FROM
    `moz-fx-data-shared-prod.telemetry.events`
)"""
```

What's new here are the `window_start` and `window_end` optional parameters that are now part of the exposure signal definition.
These parameters can be used for specifying the date range when we want to check clients for exposures. They are representing the number of days before or after the first enrollment date. There are some additional custom values that can be used:

* `enrollment_start`: equal to using `0`
* `enrollment_end`: equal to the enrollment period length in days
* `analysis_window_start`: use the start of the current analysis window
* `analysis_window_end`: use the end of the current analysis window
* some integer: specify the window with a custom value
* if parameters are not specified: default to `enrollment_start` and `enrollment_end`

So for expressing (1.) this would look like

```toml
[experiment.exposure_signal]
# ...
window_start = "analysis_window_start"
window_end = "analysis_window_end"
```

For expressing (2.):

```toml
[experiment.exposure_signal]
# ...
window_start = "enrollment_start"
window_end = "analysis_window_end"
```

The exposure signal will be used for metrics that specify `"exposures"` as one of the `analysis_bases`:

```toml
[metrics.ad_clicks]
analysis_bases = ["exposures"]
```

Results for exposure based metrics (which are computed based on only exposed clients) will be written into tables named like `<slug>_exposures_{day,week,overall}_<index>`. There is more information on accessing the data in these tables [here](https://docs.telemetry.mozilla.org/datasets/jetstream.html). Afaik, Experimenter currently only shows results for `enrollments` based metrics, but you can manually access the results. 


@rebecca-burwei Does this look like a reasonable way of expressing more flexible exposures? I'm also open to other suggestions/ideas for improvements.


It is possible to extend this concept if we want to do the same for `non_exposed` clients. We would just need to add a new `analysis_basis` to mozanalysis that could reuse the defined `ExposureSignal` (but does the opposite as `exposed`). Results would then be available for metrics that specify the `non_exposed` analysis basis in `<slug>_non_exposures_{day,week,overall}_<index>` tables.
